### ISSUE TITLE
Issue with build

### ISSUE THREAD

**Issue by sirvibegodlol** [Hqrion/Phobos-1.9.0-BUILDABLE-SRC#17]
every time I try and run a gradle command I get this error

FAILURE: Build failed with an exception.

* What went wrong:
Unable to get mutable Windows environment variable map

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

how do I fix this?

**Comment by Hqrion** [comment]
Windows problem, something is wrong with your OS or smth idk

**Comment by rxversedcode** [comment]
i got the same thing
