### ISSUE TITLE
Still ratted

### ISSUE THREAD

**Issue by v3rb13** [Hqrion/Phobos-1.9.0-BUILDABLE-SRC#4]
Still ratted
https://ibb.co/N94fsBx

**Comment by Hqrion** [comment]
Hi there, the files which you have shown in the screenshot i.e the Translator module is attempting to use it's API key to communicate with translation servers. This is not a RAT. Please research and familiarise yourself with how RATs are put into block game clients, and then determine whether it's a rat than just posting some random issue. Please do not create an issue again, thanks.
