### ISSUE TITLE
Src doesn't compile

### ISSUE THREAD

**Issue by YeahOMA** [Hqrion/Phobos-1.9.0-BUILDABLE-SRC#5]
Yes, I have a JDK and PATH set up.
Yes, I ran gradlew setupDecompWorkspace.

When I run gradlew build inside the IDE there are many errors.

**Comment by Hqrion** [comment]
Mind giving me the errors?

**Comment by YeahOMA** [comment]
https://pastebin.com/B4EgmTbS

**Comment by Hqrion** [comment]
Any broken code, please replace it from 1.7.2 sources
